upp:
    appID: exchange_pay
    environment: dev
server:
    port: 41007
spring:
    thymeleaf:
      cache: false
      mode: HTML5
    http:
      encoding:
        charset:  UTF-8
        enabled:  true
        force:  true
#开发阶段注释cat相关配置
#cat:
#  enabled: true
#  ip: 10.15.195.70:2280:8080
#  domain: cat
#kafka:
#  enabled: true
#  brokers: 10.199.204.23:9092
#  zknodes: 10.199.204.25:2181
#以下这四个参数为必须项，其他可选项请参考org.apache.tomcat.jdbc.pool.PoolConfiguration
datasource: 
  dataSource:
    url: jdbc:mysql://localhost:3306/exchange?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
redis:
  enabled: true
  database: 10
  master:
    ip: 127.0.0.1
    port: 6379
